dist: trusty
sudo: true
language: 'php'
matrix:
  include:
    - php: 7.1
      env: PHPUNIT_OPTIONS= COMPOSER_CMD=install COMPOSER_OPTS='--no-interaction --no-scripts' COMPOSER_RUN_SCRIPT='run-script post-install-cmd' MSGPACK_VERSION='2.0.2'

install:
  - composer $COMPOSER_CMD $COMPOSER_OPTS; composer $COMPOSER_RUN_SCRIPT

before_install:
  - phpenv config-rm xdebug.ini
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y neovim
  - pecl install msgpack-${MSGPACK_VERSION}

script:
  - ./vendor/bin/phpunit ${PHPUNIT_OPTIONS}
  - ./tests/vim/bin/runtests.sh
