dist: trusty
sudo: true
language: 'php'
matrix:
  include:
    - php: 5.6
      env: PHPUNIT_OPTIONS="--exclude-group php7" COMPOSER_CMD=update COMPOSER_OPTS='--no-interaction --no-scripts' COMPOSER_RUN_SCRIPT='run-script post-install-cmd'
    - php: 7.1
      env: PHPUNIT_OPTIONS= COMPOSER_CMD=install COMPOSER_OPTS='--no-interaction --no-scripts' COMPOSER_RUN_SCRIPT='run-script post-install-cmd'

install:
  - composer $COMPOSER_CMD $COMPOSER_OPTS; composer $COMPOSER_RUN_SCRIPT

before_install:
  - phpenv config-rm xdebug.ini
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y neovim
  - pecl install msgpack-0.5.7

script:
  - ./vendor/bin/phpunit ${PHPUNIT_OPTIONS}
  - ./tests/vim/runtests.sh
