imports:
    - { resource: common.yml }

services:
    view:
        class:              \PHPCD\View\VimMenuItemView

    nsinfo:
        class:              \PHPCD\NamespaceInfo
        factory:            ['@phpcd_factory', 'createNamespaceInfo']
        arguments:
            - '%root%'

    type.legacy:
        class:      \PHPCD\DocBlock\LegacyTypeLogic
        arguments:
            - '@default_logger'
            - '@file_info_factory'

    handler.phpcd:
        class:              \PHPCD\PHPCD
        arguments:
            - '@nsinfo'
            - '@default_logger'
            - '@constant_info_repository'
            - '@property_info_repository'
            - '@method_info_repository'
            - '@file_info_factory'
            - '@view'
            - '@type.legacy'

    server.phpcd:
        class:              Lvht\MsgpackRpc\ForkServer
        arguments:          [ '@messenger', '@handler.phpcd' ]
