imports:
    - { resource: common.yml }

services:
    view:
        class:              \PHPCD\View\VimMenuItemView

    nsinfo:
        class:              \PHPCD\NamespaceInfo
        arguments:
            - '%root%'

    handler.phpcd:
        class:              \PHPCD\PHPCD
        arguments:
            - '@nsinfo'
            - '@default_logger'
            - '@constant_info_repository'
            - '@property_info_repository'
            - '@method_info_repository'
            - '@file_info_factory'
            - '@view'

    server.phpcd:
        class:              Lvht\MsgpackRpc\ForkServer
        arguments:          [ '@messenger', '@handler.phpcd' ]
