imports:
    - { resource: parameters.yml }

services:
    phpcd_factory:
        class:              \PHPCD\Factory

    default_logger:
        class:              Psr\Log\LoggerInterface
        factory:            ['@phpcd_factory', 'createLogger']
        arguments:
            - '%logger_implementation%'
            - '%logger_parameters%'

    default_pattern_matcher:
        class:              \PHPCD\PatternMatcher\PatternMatcher
        factory:             ['@phpcd_factory', 'createPatternMatcher']
        arguments:           ['%completion_match_type%', '%completion_case_sensitivity%']

    subsequence_pattern_matcher:
        class:              \PHPCD\PatternMatcher\SubsequencePatternMatcher
        arguments:           ['%completion_case_sensitivity%']
        autowiring_types:   \PHPCD\PatternMatcher\PatternMatcher

    head_pattern_matcher:
        class:              \PHPCD\PatternMatcher\HeadPatternMatcher
        arguments:           ['%completion_case_sensitivity%']
        autowiring_types:   \PHPCD\PatternMatcher\PatternMatcher

    messenger:
        class:              Lvht\MsgpackRpc\Messenger
        factory:            ['@phpcd_factory', 'createMessenger']
        arguments:          ['@io', '%messenger%']

    io:
        class:              Lvht\MsgpackRpc\StdIo
        autowiring_types:   Lvht\MsgpackRpc\Io

    file_info_factory:
        class:              \PHPCD\PHPFile\PHPFileFactory

    class_info_factory:
        class:              \PHPCD\Element\ClassInfo\ReflectionClassFactory

    docblock_factory:
        class:              \phpDocumentor\Reflection\DocBlockFactory
        factory:            ['phpDocumentor\Reflection\DocBlockFactory', 'createInstance']

    factory.context:
        class:              \phpDocumentor\Reflection\Types\ContextFactory

    docblock:
        class:              PHPCD\DocBlock\DocBlock
        arguments:
            - '@docblock_factory'
            - '@factory.context'

    repository.constant.factory:
        class:              \PHPCD\Element\ConstantInfo\ConstantFactory

    repository.constant:
        class:              \PHPCD\Element\ConstantInfo\RuntimeConstantRepository
        arguments:          ['@default_pattern_matcher', '@repository.constant.factory']

    repository.constant.class:
        class:              \PHPCD\Element\ConstantInfo\ReflectionClassConstantRepository
        arguments:          ['@default_pattern_matcher', '@class_info_factory']

    method_info_repository:
        class:              \PHPCD\Element\ObjectElement\ReflectionMethodRepository
        arguments:
            - '@default_pattern_matcher'
            - '@class_info_factory'
            - '@docblock'

    property_info_repository:
        class:              \PHPCD\Element\ObjectElement\ReflectionPropertyRepository
        arguments:
            - '@default_pattern_matcher'
            - '@class_info_factory'
            - '@docblock'

    view:
        class:              \PHPCD\View\VimMenuItemView

    nsinfo:
        class:              \PHPCD\NamespaceInfo
        factory:            ['@phpcd_factory', 'createNamespaceInfo']
        arguments:
            - '%root%'

    function_factory:
        class:               \PHPCD\Element\FunctionInfo\FunctionFactory
        arguments:
            - '@docblock'

    function_repository:
        class:               \PHPCD\Element\FunctionInfo\RuntimeFunctionRepository
        arguments:
            - '@default_pattern_matcher'
            - '@function_factory'

    handler.phpcd:
        class:              \PHPCD\PHPCD
        arguments:
            - '@nsinfo'
            - '@default_logger'
            - '@repository.constant'
            - '@repository.constant.class'
            - '@property_info_repository'
            - '@method_info_repository'
            - '@file_info_factory'
            - '@view'
            - '@function_repository'

    server.phpcd:
        class:              Lvht\MsgpackRpc\ForkServer
        arguments:          [ '@messenger', '@handler.phpcd' ]

    class_loader:
        class:              \PHPCD\Element\ClassInfo\ClassLoader\ClassLoader
        factory:            ['@phpcd_factory', 'createClassLoader']
        arguments:
            - '%class_loader%'

    classes_repository:
        class:              \PHPCD\Element\ClassInfo\ComposerClassmapFileRepository
        arguments:          ['@class_loader', '@default_pattern_matcher', '@class_info_factory', '@file_info_factory', '@default_logger']

    handler.phpid:
        class:              \PHPCD\PHPID
        arguments:          ['%root%', '@default_logger', '@classes_repository']
        # calls:
        #     - [ index ]

    server.phpid:
        class:              Lvht\MsgpackRpc\ForkServer
        arguments:          [ '@messenger', '@handler.phpid' ]
